# **Pandas**
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

### **Pandas Series**

It is a one-dimensional array holding data of any type.

### Creating Series

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
wlabels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

# **Pandas Dataframe**

### Creating Dataframe

In [ ]:
data = {
    'Name' : ['John','Aditi','Yash','puja'],
    'Age':[25,26,21,28],
    'City':['Delhi','Mumbai','Banglore','Pune'],
    'Salary':[65000,50000,45000,80000]
}
df= pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   25     Delhi   65000
1  Aditi   26    Mumbai   50000
2   Yash   21  Banglore   45000
3   puja   28      Pune   80000

In [ ]:
data_list = [
    ['John',25,'Delhi',65000],
    ['Aditi',26,'Mumbai',50000],
    ['Yash',21,'Banglore',45000],
    ['Puja',28,'Pune',80000]
]
df2= pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)

In [ ]:
df2

    Name  Age      City  Salary
0   John   25     Delhi   65000
1  Aditi   26    Mumbai   50000
2   Yash   21  Banglore   45000
3   Puja   28      Pune   80000

## **Selection & Indexing od Column**

In [ ]:
df2

    Name  Age      City  Salary
0   John   25     Delhi   65000
1  Aditi   26    Mumbai   50000
2   Yash   21  Banglore   45000
3   Puja   28      Pune   80000

In [ ]:
df2[["Name","City"]]

    Name      City
0   John     Delhi
1  Aditi    Mumbai
2   Yash  Banglore
3   Puja      Pune

## **Creating a new column**

In [ ]:
df2["Designation"] = ["Doctor","Teacher","Engineer","Doctor"]
df2

    Name  Age      City  Salary Designation
0   John   25     Delhi   65000      Doctor
1  Aditi   26    Mumbai   50000     Teacher
2   Yash   21  Banglore   45000    Engineer
3   Puja   28      Pune   80000      Doctor

## **Removing Column**

In [ ]:
df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   25     Delhi   65000
1  Aditi   26    Mumbai   50000
2   Yash   21  Banglore   45000
3   Puja   28      Pune   80000

In [ ]:
df2

    Name  Age      City  Salary Designation
0   John   25     Delhi   65000      Doctor
1  Aditi   26    Mumbai   50000     Teacher
2   Yash   21  Banglore   45000    Engineer
3   Puja   28      Pune   80000      Doctor

## **Selecting Rows**

In [ ]:
df2

    Name  Age      City  Salary Designation
0   John   25     Delhi   65000      Doctor
1  Aditi   26    Mumbai   50000     Teacher
2   Yash   21  Banglore   45000    Engineer
3   Puja   28      Pune   80000      Doctor

In [ ]:
df2.loc[[0,1]]

    Name  Age    City  Salary Designation
0   John   25   Delhi   65000      Doctor
1  Aditi   26  Mumbai   50000     Teacher

In [ ]:
df.iloc[3]

Name       puja
Age          28
City       Pune
Salary    80000
Name: 3, dtype: object

## **Selecting subsets of rows and columns**

In [ ]:
df2.loc[[0,1]][["City","Salary"]]

     City  Salary
0   Delhi   65000
1  Mumbai   50000

## **Conditional Selection**

In [ ]:
df2

    Name  Age      City  Salary Designation
0   John   25     Delhi   65000      Doctor
1  Aditi   26    Mumbai   50000     Teacher
2   Yash   21  Banglore   45000    Engineer
3   Puja   28      Pune   80000      Doctor

In [ ]:
#I only want to show those people whose age is above 25.

In [ ]:
df2[df2["Age"] > 25]

    Name  Age    City  Salary Designation
1  Aditi   26  Mumbai   50000     Teacher
3   Puja   28    Pune   80000      Doctor

In [ ]:
#I only want those whose age is above 25 and they are from pune.

In [ ]:
df2[(df2["Age"] > 25) & (df2["City"] == 'Pune')]

   Name  Age  City  Salary Designation
3  Puja   28  Pune   80000      Doctor

## **Find missing data**

In [ ]:
data = {
    'A': [1,2,3,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [ ]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()

A    0
B    1
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

## **Removing missing Data**

In [ ]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [ ]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [ ]:
df.dropna(thresh=3)

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
4  5  5.0  NaN  5.0

## **Filling the missing Data**

In [ ]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [ ]:
df = df.fillna(0)

In [ ]:
df

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [ ]:
values = {'A':0,'B':1,"C": 20,'D':200}
df.fillna(value=values)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [ ]:
df

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [ ]:
df.fillna(df.mean())

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0