## **Merging ,Joining & Concatenation**

In [ ]:
import numpy as np
import pandas  as pd

**Merging 2 dataframes**

In [ ]:
employees = pd.DataFrame({
    'employee_id':[101,102,103,104,105],
    'name':['Anjali','Yash','Raha','puja','mit'],
    'department':['HR','IT','Finance','IT','Marketing']
})

#dataframe2
salaries = pd.DataFrame({
    'employee_id':[101,102,103,7,8],
    'Salary':[60000,50000,40000,50000,45000],
    'Bonus':[2000,4000,6000,3000,4000]
})

In [ ]:
employees

   employee_id    name department
0          101  Anjali         HR
1          102    Yash         IT
2          103    Raha    Finance
3          104    puja         IT
4          105     mit  Marketing

In [ ]:
salaries

   employee_id  Salary  Bonus
0          101   60000   2000
1          102   50000   4000
2          103   40000   6000
3            7   50000   3000
4            8   45000   4000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id    name department  Salary  Bonus
0          101  Anjali         HR   60000   2000
1          102    Yash         IT   50000   4000
2          103    Raha    Finance   40000   6000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id    name department   Salary   Bonus
0            7     NaN        NaN  50000.0  3000.0
1            8     NaN        NaN  45000.0  4000.0
2          101  Anjali         HR  60000.0  2000.0
3          102    Yash         IT  50000.0  4000.0
4          103    Raha    Finance  40000.0  6000.0
5          104    puja         IT      NaN     NaN
6          105     mit  Marketing      NaN     NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id    name department   Salary   Bonus
0          101  Anjali         HR  60000.0  2000.0
1          102    Yash         IT  50000.0  4000.0
2          103    Raha    Finance  40000.0  6000.0
3          104    puja         IT      NaN     NaN
4          105     mit  Marketing      NaN     NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id    name department  Salary  Bonus
0          101  Anjali         HR   60000   2000
1          102    Yash         IT   50000   4000
2          103    Raha    Finance   40000   6000
3            7     NaN        NaN   50000   3000
4            8     NaN        NaN   45000   4000

### **Concatination of 2 Dataframes**

In [ ]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
    })

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
    })

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### **Joining 2 dataframes**

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alaya', 'Bonny', 'Charles']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [76, 80, 98]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alaya
2    Bonny
3  Charles

In [ ]:
df2

   score
2     76
3     80
4     98

In [ ]:
df1.join(df2,how='outer')

      name  score
1    Alaya    NaN
2    Bonny   76.0
3  Charles   80.0
4      NaN   98.0

In [ ]:
df2.join(df1)

   score     name
2     76    Bonny
3     80  Charles
4     98      NaN

## **GroupBy Aggregation**

In [ ]:

data = {
    'Category': ['s1', 's2', 's1', 's2', 's1', 's2', 's1', 's2'],
    'Store': ['x', 'y', 'y', 'y', 'x', 'y', 'y', 'x'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0       s1     x    100        10 2023-01-01
1       s2     y    200        15 2023-01-02
2       s1     y    150        12 2023-01-03
3       s2     y    250        18 2023-01-04
4       s1     x    120         8 2023-01-05
5       s2     y    180        20 2023-01-06
6       s1     y    200        15 2023-01-07
7       s2     x    300        25 2023-01-08

Group by categories and calculate the sum of sales

In [ ]:
col = df.groupby('Category')
col
for i,j in col:
    print(i)
    print(j)

s1
  Category Store  Sales  Quantity       Date
0       s1     x    100        10 2023-01-01
2       s1     y    150        12 2023-01-03
4       s1     x    120         8 2023-01-05
6       s1     y    200        15 2023-01-07
s2
  Category Store  Sales  Quantity       Date
1       s2     y    200        15 2023-01-02
3       s2     y    250        18 2023-01-04
5       s2     y    180        20 2023-01-06
7       s2     x    300        25 2023-01-08

In [ ]:
col = df.groupby('Category')['Sales'].sum()
col

Category
s1    570
s2    930
Name: Sales, dtype: int64

Group by sales and calculate the sum of sales

In [ ]:
col = df.groupby('Store')['Sales'].sum()
col

Store
x    520
y    980
Name: Sales, dtype: int64

**Group by multiple columns**
**Group by Category and Store**

In [ ]:
col = df.groupby(['Category','Store'])['Sales'].sum()
col

Category  Store
s1        x        220
          y        350
s2        x        300
          y        630
Name: Sales, dtype: int64

**Aggregation**

In [ ]:
df['Sales'].mean()
'''mean median mode min max count std'''

np.float64(187.5)

In [ ]:
df['Sales'].agg(['sum','mean','min','max','count','std','median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

## **PIVOT TABLES**

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    835     77   John  January      Q1
1  2023-01-02       B   West    673     35   Mary  January      Q1
2  2023-01-03       C  North    380     63    Bob  January      Q1
3  2023-01-04       D  South    273     56  Alice  January      Q1
4  2023-01-05       A   East    100     91   John  January      Q1
5  2023-01-06       B   West    201     58   Mary  January      Q1
6  2023-01-07       C  North    342     24    Bob  January      Q1
7  2023-01-08       D  South    158     27  Alice  January      Q1
8  2023-01-09       A   East    970     72   John  January      Q1
9  2023-01-10       B   West    760     95   Mary  January      Q1
10 2023-01-11       C  North    614     73    Bob  January      Q1
11 2023-01-12       D  South    989     83  Alice  January      Q1
12 2023-01-13       A   East    908     99   John  January      Q1
13 2023-01-14       B   West    220     27   Mary  January      Q1
14 2023-01-15       C  North    938     50    Bob  January      Q1
15 2023-01-16       D  South    455     14  Alice  January      Q1
16 2023-01-17       A   East    924     10   John  January      Q1
17 2023-01-18       B   West    148     29   Mary  January      Q1
18 2023-01-19       C  North    970     84    Bob  January      Q1
19 2023-01-20       D  South    533     71  Alice  January      Q1

In [ ]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     908.0    NaN    NaN    NaN
North      NaN    NaN  614.0    NaN
South      NaN    NaN    NaN  455.0
West       NaN  220.0    NaN    NaN

In [ ]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     747.4    NaN    NaN    NaN  69.8   NaN   NaN   NaN
North      NaN    NaN  648.8    NaN   NaN   NaN  58.8   NaN
South      NaN    NaN    NaN  481.6   NaN   NaN   NaN  50.2
West       NaN  400.4    NaN    NaN   NaN  48.8   NaN   NaN

### **Cross Tabs**

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### **Operations**

DataFrames Basic Operations

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A'] + 20

0    21
1    22
2    23
3    24
4    25
Name: A, dtype: int64

**Dataframes applying functions**

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
def square(x):
  return x**2

In [ ]:
df1["D"]= df1["B"].apply(square)

In [ ]:
df1

      A   B    C     D
0   100  10  100   100
1   400  20  200   400
2   900  30  300   900
3  1600  40  400  1600
4  2500  50  500  2500